public class Test {
    
    public Test(){
        Integer a; 	// new Integer(23);
        System.debug('---> Value in A : ' + a);	//null 
        
        /*Integer []arr ; 
        arr = new Integer[]{34,4,3,4,3,4,3,5,656};
        arr[1] = 7734; 
        System.debug('---> First  Value in Array Arr : ' + arr[0]);
        System.debug('---> Second Value in Array Arr : ' + arr[1]);
        //arr[6] = 8384;
        System.debug('---> Values in Array Arr : ' + arr);
        
        List<Integer> firstArr  = new List<Integer>();
        System.debug('----> Data in Array First : ' + firstArr );
        
        firstArr.add(824);
        firstArr.add(873);
        firstArr.add(122);
        firstArr.add(9766);
        System.debug('----> Data in Array First : ' + firstArr );
        firstArr.add(0,22);
        System.debug('----> Data in Array First : ' + firstArr );*/
        
    }
}